@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

### tasks
GET {{host}}/tasks

### tasks
GET {{host}}/tasks/fd473255-971c-4fb4-befb-574045791da5

### Create Task
@title = Clean my room
@description = Lots of cleanning has to be done
@status = OPEN

POST {{host}}/tasks HTTP/1.1
Content-Type: {{contentType}}

{
    "title": "{{title}}",
    "description": "{{description}}",
    "status": "{{status}}"
}